[global]
type=global
user_agent=Webphone Lab

[transport-ws]
type=transport
protocol=ws
bind=0.0.0.0
allow_reload=yes

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
allow_reload=yes

[webrtc-endpoint](!)
type=endpoint
transport=transport-ws
context=internal
disallow=all
allow=opus,ulaw,alaw,vp8,h264
webrtc=yes
use_avpf=yes
media_encryption=dtls
dtls_auto_generate_cert=yes
dtls_setup=actpass
ice_support=yes
media_use_received_transport=yes
rtcp_mux=yes
rewrite_contact=yes
force_rport=yes
rtp_symmetric=yes
direct_media=no
timers=yes

[webrtc-aor](!)
type=aor
max_contacts=2
remove_existing=yes

[auth-userpass](!)
type=auth
auth_type=userpass

[1001](webrtc-aor)

[1001-auth](auth-userpass)
username=1001
password=SenhaForte123

[1001](webrtc-endpoint)
aors=1001
auth=1001-auth
callerid="Ramal 1001" <1001>

[1002](webrtc-aor)

[1002-auth](auth-userpass)
username=1002
password=SenhaForte456

[1002](webrtc-endpoint)
aors=1002
auth=1002-auth
callerid="Ramal 1002" <1002>

#include pjsip_users.conf
