; Gerado automaticamente pela API — não editar
; Atualizado: 2026-04-03 17:52:18

[2000](webrtc-aor)

[2000-auth](auth-userpass)
username=2000
password=dc68791d7b3dc8ce

[2000](webrtc-endpoint)
aors=2000
auth=2000-auth
callerid="João Teste" <2000>

[2001](webrtc-aor)

[2001-auth](auth-userpass)
username=2001
password=a0fcf45d12ccb7b9

[2001](webrtc-endpoint)
aors=2001
auth=2001-auth
callerid="Marcio Ribeiro da Cruz" <2001>

[2002](webrtc-aor)

[2002-auth](auth-userpass)
username=2002
password=633ae8a1cc0aca74

[2002](webrtc-endpoint)
aors=2002
auth=2002-auth
callerid="MARIA VALDENEUDA SOUZA CRUZ" <2002>

[2003](webrtc-aor)

[2003-auth](auth-userpass)
username=2003
password=c71afec2f7ca1d1d

[2003](webrtc-endpoint)
aors=2003
auth=2003-auth
callerid="Teste Reload" <2003>
